# The University of Melbourne, School of Computing and Information Systems
# COMP30027 Machine Learning, 2019 Semester 1
-----
## Practical, Week 2 - sample solutions

In [1]:
import numpy as np
from math import sqrt
from time import time
import random

#### Question 2

In [2]:
#Q2a
a = np.array([0,1,2,3,4])
b = np.array([1,3,-2,0,0])
print(a+b)
print(a-b)
print(3*b - 2*a)

[1 4 0 3 4]
[-1 -2  4  3  4]
[  3   7 -10  -6  -8]


In [3]:
#Q2b
def my_euclidean_dist(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return sqrt(sum([(a[i]-b[i])*(a[i]-b[i]) for i in range(len(a))]))
print(my_euclidean_dist(a,b))

6.782329983125268


In [4]:
#Q2c
def my_hamming(a,b):
    assert len(a)==len(b), "Lists are of different lengths!"
    return sum([a[i]!=b[i] for i in range(len(a))])
print(my_hamming([0,"cat",800,"??"],[1,"dog",-266,"??"]))

3


There are 3 different elements in these lists; of the four elements, only "??" is shared.

Due to the mixture of data types, these have to be Python lists, not numpy arrays.

#### Question 3

In [5]:
#Q3a
def my_dot(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return sum([a[i]*b[i] for i in range(len(a))])
print(my_dot(np.array([1,2]),np.array([1,1])))
print(my_dot(np.array([1,2]),np.array([2,2])))
print(my_dot(np.array([1,2]),np.array([3,3])))
print(my_dot(np.array([0,0,1]),np.array([1,0,0])))

3
6
9
0


In [6]:
#Q3b
def clumsy_cos(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return (my_dot(a,b)/(my_euclidean_dist(a,np.array([0]*len(a))) * my_euclidean_dist(b,np.array([0]*len(b)))))
print(clumsy_cos(np.array([1,2]),np.array([1,1])))
print(clumsy_cos(np.array([1,2]),np.array([2,2])))
print(clumsy_cos(np.array([1,2]),np.array([3,3])))
print(clumsy_cos(np.array([0,0,1]),np.array([1,0,0])))

0.9486832980505138
0.9486832980505138
0.9486832980505138
0.0


Cosine is a function of the angle between two vectors. For the first three examples, the cosine value is the same, because the second vector changes in length, but not in direction.

For the fourth example, it is obvious that the cosine will be 0, because the dot product is 0 - here, the two vectors are perpendicular.

In [7]:
#Q3c
def my_cosine_numpy(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return (np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)))
print(clumsy_cos(a,b))
print(my_cosine_numpy(a,b))

# Number of dimensions in each vector, where each element is a random floating-point number between 0 and 1
nd = 2

random.seed(12345)
start = time()
for j in range(1000000):
    clumsy_cos([random.random() for i in range(nd)],[random.random() for i in range(nd)])
end = time()
print ("Clumsy: ",end-start, "seconds")

random.seed(12345)
start = time()
for j in range(1000000):
    my_cosine_numpy([random.random() for i in range(nd)],[random.random() for i in range(nd)])
end = time()
print ("Numpy: ",end-start, "seconds")

-0.048795003647426664
-0.048795003647426664
Clumsy:  34.03769588470459 seconds
Numpy:  19.394791841506958 seconds


The numpy version is clearly faster, and the difference between them is greater as the dimensionality increases.

If you check the various parts of the calculation (of which there are five: the dot product, the two vector lengths, one division, and one multiplication), the numpy version is just faster everywhere. Particularly egregious, however, is the method of finding a vector length by using our Euclidean distance function with a dummy vector of all zeroes.

#### Question 4

In [8]:
#Q4
M = np.array([[1,2,3],[4,2,1],[6,2,0]])
N = np.array([[0,3,1],[1,1,4],[2,0,3]])

print("M*N",M*N)
print("M.N",np.dot(M,N))
print("N*M",N*M)
print("N.M",np.dot(N,M))
print("M*M",M*M)
print("M**2",M**2)
print("M.M",np.dot(M,M))

M*N [[ 0  6  3]
 [ 4  2  4]
 [12  0  0]]
M.N [[ 8  5 18]
 [ 4 14 15]
 [ 2 20 14]]
N*M [[ 0  6  3]
 [ 4  2  4]
 [12  0  0]]
N.M [[18  8  3]
 [29 12  4]
 [20 10  6]]
M*M [[ 1  4  9]
 [16  4  1]
 [36  4  0]]
M**2 [[ 1  4  9]
 [16  4  1]
 [36  4  0]]
M.M [[27 12  5]
 [18 14 14]
 [14 16 20]]


You can probably see that the multiplication (and exponentiation) operation happens element-wise, namely:
$MN[i][j] = M[i][j] * N[i][j]$

This is actually convenient in certain contexts, but is certainly not how we typically wish to multiply matrices!